[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "*"
gloo = "*"
serde = "*"
serde_json = "*"
stylist = { version = "*", features = ["yew", "yew_integration"] }
wasm-bindgen = "*"
web-sys = { version = "*", features = ["HtmlInputElement"] }
yew-oauth2 = "*"
yew-router = "*"
yewdux = "*"
gloo-net = "*"
wasm-bindgen-futures = "*"
hive = { path = "../engine" }
