version: '3'

services:
  frontend:
    build: 
      dockerfile: ../oci-images/frontend
    command: bash -c "cd app/frontend && trunk serve --address 0.0.0.0 --port ${TRUNK_SERVE_PORT:-8080}"
    environment:
      - ACTIX_PORT=${ACTIX_PORT:-8081}
      - TRUNK_SERVE_PORT=${TRUNK_SERVE_PORT:-8080}
    ports:
      - "${TRUNK_SERVE_PORT:-8080}:${TRUNK_SERVE_PORT:-8080}"
    volumes:
      - type: bind
        source: ../
        target: /app
      - /app/frontend/target

  backend:
    build: 
      dockerfile: ../oci-images/backend
    command: bash -c "cd app/backend && cargo watch -x \"run\""
    environment:
      - ACTIX_PORT=${ACTIX_PORT:-8081}
      - TRUNK_SERVE_PORT=${TRUNK_SERVE_PORT:-8080}
      - TRUNK_SERVE_HOST=localhost
      - RUST_LOG=info
    ports:
      - "${ACTIX_PORT:-8081}:${ACTIX_PORT:-8081}"
    volumes:
      - type: bind
        source: ../
        target: /app
      - /app/backend/target
